//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2018.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2018.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -10
        ///-12
        ///+1
        ///+14
        ///+11
        ///-19
        ///-4
        ///+10
        ///+10
        ///-12
        ///-13
        ///-10
        ///-8
        ///+11
        ///+3
        ///-10
        ///+8
        ///+5
        ///-14
        ///+7
        ///+12
        ///+12
        ///+14
        ///-1
        ///+17
        ///-5
        ///+9
        ///-15
        ///+8
        ///-16
        ///+9
        ///+6
        ///+17
        ///-11
        ///+19
        ///+11
        ///-9
        ///-1
        ///-8
        ///-16
        ///-5
        ///+6
        ///+2
        ///+6
        ///+12
        ///+15
        ///+16
        ///-6
        ///-8
        ///-5
        ///+11
        ///-9
        ///+19
        ///+19
        ///-5
        ///-12
        ///-17
        ///-20
        ///+9
        ///-6
        ///-2
        ///+20
        ///+15
        ///-8
        ///+15
        ///+19
        ///-5
        ///-17
        ///-9
        ///+1
        ///-9
        ///-11
        ///-19
        ///-1
        ///-15
        ///+18
        ///-4
        ///+19
        ///+3
        ///+21
        ///+5
        ///-1
        ///+8
        ///+9
        ///+9
        ///-16
        ///+17
        ///-15
        ///+18
        ///+14
        ///+8
        ///-13
        ///-2
        ///-15
        ///+13
        ///+19
        ///-13
        ///+5
        ///+16
        ///+16
        ///+7
        ///+8
        ///-19
        ///+3
        ///-12
        ///+18
        ///-16
        ///-19
        ///+8
        ///-16
        ///+20
        ///+15
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdventOfCode_Day1 {
            get {
                return ResourceManager.GetString("AdventOfCode_Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -2  
        ///+4
        ///-2
        ///+4   
        ///-2   
        ///+4
        ///+456456
        ///-1231231.
        /// </summary>
        internal static string AdventOfCode_Day1_test {
            get {
                return ResourceManager.GetString("AdventOfCode_Day1_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icxjubroqtunzeyzpomfksahgw
        ///ibxjvbroqtunleyzjdmfksahow
        ///icxjvbroqtinleyzpdmflsahnw
        ///icxjvbnoqtunleyvpgmfksahgw
        ///wcxjvbroqrunleyzpdmfksahge
        ///icxjtbroqtjzleyzpdmfksahgw
        ///icxjvbrohtunleyzpdmfkbahsw
        ///xcxjvbroqcunleyzpdmfksaxgw
        ///ycxjvbroqtunleyzpowfksahgw
        ///icxfvbroqtunleyzpdmfksncgw
        ///ixxjvbuoqtunleyzpdvfksahgw
        ///icfjvbroqtunleyzpdmfksadgt
        ///icxjvbroqdunleyzpdafksqhgw
        ///icxjvbrobtunlelzpdmfkuahgs
        ///ujxjvbroqtunleyzpdmqksahgw
        ///icqjvsroqtunleyzpdmfksahuw
        ///icxjvbroptpnleyzpdmfksangw
        ///ipxjvbroqtunleyzpdmfesahgi
        ///icajvbro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdventOfCode_Day2 {
            get {
                return ResourceManager.GetString("AdventOfCode_Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcdefghabcda
        ///acbdefghawxyz
        ///aaaitghlkfmsd
        ///abbcccddyuiop
        ///abcdgfghabcda
        ///lasdfasdhkjha
        ///sdfalkajsdlal
        ///dfacsdfreasdd.
        /// </summary>
        internal static string AdventOfCode_Day2_test {
            get {
                return ResourceManager.GetString("AdventOfCode_Day2_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 896,863: 29x19
        ///#2 @ 367,315: 15x26
        ///#3 @ 53,233: 21x25
        ///#4 @ 581,238: 13x24
        ///#5 @ 677,75: 17x17
        ///#6 @ 130,597: 21x12
        ///#7 @ 362,788: 29x11
        ///#8 @ 139,784: 27x12
        ///#9 @ 18,968: 16x25
        ///#10 @ 690,473: 10x15
        ///#11 @ 791,508: 26x24
        ///#12 @ 648,35: 12x26
        ///#13 @ 30,697: 14x17
        ///#14 @ 726,670: 24x16
        ///#15 @ 70,418: 11x23
        ///#16 @ 115,456: 17x16
        ///#17 @ 734,678: 21x22
        ///#18 @ 457,627: 22x18
        ///#19 @ 793,835: 10x24
        ///#20 @ 70,440: 26x29
        ///#21 @ 756,515: 25x21
        ///#22 @ 151,570: 16x18
        ///#23 @ 297,592: 24x16
        ///#24 @ 432,339: 24x22
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdventOfCode_Day3 {
            get {
                return ResourceManager.GetString("AdventOfCode_Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 3,10: 5x5
        ///#2 @ 7,13: 4x7
        ///#3 @ 5,8: 8x2
        ///#4 @ 12,12: 3x3
        ///#5 @ 1,1: 2x2.
        /// </summary>
        internal static string AdventOfCode_Day3_test {
            get {
                return ResourceManager.GetString("AdventOfCode_Day3_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-04-22 00:52] wakes up
        ///[1518-05-16 00:00] Guard #1319 begins shift
        ///[1518-03-24 00:50] wakes up
        ///[1518-11-12 00:47] wakes up
        ///[1518-08-18 00:42] falls asleep
        ///[1518-04-24 00:49] wakes up
        ///[1518-06-03 00:52] wakes up
        ///[1518-10-08 00:52] wakes up
        ///[1518-10-14 23:56] Guard #3359 begins shift
        ///[1518-04-07 00:41] wakes up
        ///[1518-11-03 00:07] wakes up
        ///[1518-07-08 00:29] falls asleep
        ///[1518-09-27 00:04] Guard #547 begins shift
        ///[1518-09-26 00:35] falls asleep
        ///[1518-07-15 00:52] wakes up
        ///[1518-06-08 00:36] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdventOfCode_Day4 {
            get {
                return ResourceManager.GetString("AdventOfCode_Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hack_Bold {
            get {
                object obj = ResourceManager.GetObject("Hack_Bold", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Hack_Regular {
            get {
                object obj = ResourceManager.GetObject("Hack_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
